# Default values for currency.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: 100.69.158.196/internal-trading
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

nodeport: 3011

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:496403030999:certificate/c789b806-1990-4ff0-8e95-011a9727b80c
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/ingress.class: alb
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  path: /*

  hosts:
    - mainnet-trading.faldax.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
   cpu: 1024m
   memory: 1500Mi
  requests:
   cpu: 128m
   memory: 256Mi

nodeSelector: {}

tolerations:
- key: kops.k8s.io/instancegroup
  operator: Equal
  value: internal-trading
  effect: NoSchedule

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kops.k8s.io/instancegroup
          operator: In
          values:
          - internal-trading

controller:
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 60

health:
  enable: true
  livenessProbe:
    path: /api/v1/tradding/system-health-check
    port: 3011
    initialDelaySeconds: 120
    periodSeconds: 30
    failureThreshold: 5
    successThreshold: 1
    timeoutSeconds: 5
  readinessProbe:
    path: /api/v1/tradding/system-health-check
    port: 3011
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 5
    successThreshold: 1
    timeoutSeconds: 5
